server:
  port: 8001
  context-path: /swagger
debug: true

spring:
  datasource:
    url: jdbc:mysql://120.79.149.128:13306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Hjr780585!
  jpa:
    show-sql: true






