spring:
  profiles:
    active: ${ENV:dev}
  jackson:
    default-property-inclusion: non_null
    #jackjson驼峰策略
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true






